Added Article page
Dimaskao/ITEA-PHP-Adv7_News-Portal pull request #2
Opened 2020-08-31 10:27 UTC by Dimaskao

2020-08-31 17:47 UTC, greeflas requested changes

2020-08-31 17:47 UTC, greeflas commented on src/Controller/ArticleController.php
> +class ArticleController extends AbstractController
Можно сделать final

2020-08-31 17:47 UTC, greeflas commented on src/Controller/ArticleController.php
> +     * @Route("/article", methods={"GET"}, name="article")
К названии лучше добавить префикс `app_`.

2020-08-31 17:47 UTC, greeflas commented on src/Service/ArticlePageFakeProvider.php
> +class ArticlePageFakeProvider implements ArticlePageProviderInterface
Можно сделать final.

2020-08-31 17:47 UTC, greeflas commented on src/Service/ArticlePageFakeProvider.php
> +        $article = [];
А для чего массив?

2020-08-31 17:47 UTC, greeflas commented on src/Service/ArticlePageProviderInterface.php
> +    public function getArticle();
Почему не указан возвращаемы тип данных?

2020-08-31 17:47 UTC, greeflas commented on src/ViewModel/ArticlePage.php
> +class ArticlePage
Можно сделать final.

2020-08-31 17:47 UTC, greeflas commented on src/ViewModel/ArticlePage.php
> +    private string $Description;
Лучше назвать `body` так как это основной текст статьи.

2020-08-31 17:47 UTC, greeflas commented on templates/home/index.html.twig
> +                <a href="article/?id={{ latesArticle.id }}">
URL адреса нужно генерировать https://symfony.com/doc/current/routing.html#generating-urls-in-templates

2020-09-01 17:50 UTC, maxim-kravets requested changes

2020-09-01 17:50 UTC, maxim-kravets commented on src/Service/ArticlePageFakeProvider.php
> +    private object $article;
Должен быть более конкретный тип свойства, аналогичный типу возвращаемого значения createArticle()

2020-09-01 17:50 UTC, maxim-kravets commented on src/Service/ArticlePageFakeProvider.php
>      }
У вас метод, судя по названию и логике, возвращает один экземпляр статьи, зачем вам цикл? Даже если значение self::ARTICLES_COUNT будет равным 100, метод вернет один экземпляр, но метод зачем-то будет создавать объект за объектом и перезаписывать предыдущий.

2020-09-02 09:02 UTC, maxim-kravets requested changes

2020-09-02 09:02 UTC, maxim-kravets commented on src/Service/ArticlePageFakeProvider.php
>  final class ArticlePageFakeProvider implements ArticlePageProviderInterface
ArticlePageFakeProvider, ArticlePage - не релевантные названия для классов, так как мы в них оперируем не страницей статьи, а сущностью, самой статьей.

2020-09-02 16:12 UTC, maxim-kravets requested changes

2020-09-02 16:12 UTC, maxim-kravets commented on src/Controller/ArticleController.php
>      public function article(): Response
в этом экшне необходимо выводит страницу page not found, если статья с нужным id не найдена

2020-09-02 16:37 UTC, Dimaskao commented on src/Controller/ArticleController.php
>      public function article(): Response
Так у нас нет БД, как можно сделать проверку если id ни на что не влияет

2020-09-02 17:49 UTC, greeflas commented on src/Controller/ArticleController.php
>      public function article(): Response
@Dimaskao можно в сервисе сымитировать эту ситуацию так как пока что мы используем фейковые данные.

2020-09-04 19:30 UTC, merged