Edded CategoryPdge
Dimaskao/ITEA-PHP-Adv7_News-Portal pull request #4
Opened 2020-09-07 18:13 UTC by Dimaskao

2020-09-09 18:12 UTC, greeflas requested changes

2020-09-09 18:12 UTC, greeflas commented on migrations/Version20200905202454.php
> +final class Version20200905202454 extends AbstractMigration
Почему в реквесте две одинаковые миграции?

2020-09-09 18:12 UTC, greeflas commented on src/Collection/CategoryPageArticles.php
> +final class CategoryPageArticles
Коллекция должна быть итератором.

2020-09-09 18:12 UTC, greeflas commented on src/Collection/CategoryPageArticles.php
> +    public function __construct($articles)
Нужно типизировать этот аргумент.

2020-09-09 18:12 UTC, greeflas commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
Если в категории нет статей - на странице категории выводим сообщение об этом. А вот если категории не существует - тогда нужно показать страницу 404.

2020-09-09 18:12 UTC, greeflas commented on src/DataFixtures/ArticleFixtures.php
> +        $categories = $manager->getRepository(Category::class)->findAll();
в фикстурах сущость нужно доставать через `$this->getReference()`.

2020-09-09 18:12 UTC, greeflas commented on src/DataFixtures/CategoryFixture.php
> +            $manager->persist($cat);
А тут добавлять через `$this->addReference()`.

2020-09-09 18:12 UTC, greeflas commented on src/Entity/Article.php
>      public function __construct(string $title)
В конструктор нужно добавить категорию так как она не может существовать без категории.

2020-09-09 18:12 UTC, greeflas commented on src/Entity/Article.php
> +    public function addCategory(?Category $category): self
А этот метод удалить.

2020-09-09 18:12 UTC, greeflas commented on src/Entity/Category.php
> +    public function setName(string $name): self
Нужно принимать в конструкторе.

2020-09-09 18:12 UTC, greeflas commented on src/Entity/Category.php
> +    public function addArticle(Article $article): self
Метод не используется, можно удалить.

2020-09-09 18:12 UTC, greeflas commented on src/Entity/Category.php
> +    public function removeArticle(Article $article): self
Метод не используется, можно удалить.

2020-09-09 18:12 UTC, greeflas commented on src/Repository/CategoryRepository.php
> +        $category = $em
Тут нужно использовать `$this->createQueryBuilder()` и join для статей.

2020-09-09 18:12 UTC, greeflas commented on src/Repository/CategoryRepository.php
> +    public function getArticleBySlug(string $slug): CategoryPageArticles
Метод должен возвращать сущность, а не коллекцию.

2020-09-09 18:12 UTC, greeflas commented on src/Service/CategoryPageProvider.php
> +    public function returnOnlyPublishedArticles($articles)
Нужно в самом SQL запросе указать, что мы хотим получить только опубликованные статьи.

2020-09-09 18:12 UTC, greeflas commented on templates/_header.html.twig
> +                <a class="nav-link" href="/category/world">World</a>
Нужно использовать `path()`.

2020-09-10 13:27 UTC, Dimaskao commented on src/DataFixtures/CategoryFixture.php
> +            $manager->persist($cat);
Что-то не получается. Если я пишу так:
```php
foreach (self::CATEGORIES as $category) {
            $cat = new Category();
            $cat->setName($category);
            $manager->persist($cat);
            
            $this->addReference('categoryReference', $cat);
        }
```
то выдает ошибку `Reference to "categoryReference" already exists, use method setReference in order to override it`, как я понял, это из за цикла.

Пробовал вызвать `$this->addReference('categoryReference', new Category());` после цикла. Но поидее создается просто пустая сущность `Category`, потому что выдает ошибку `Typed property App\Entity\Category::$name must not be accessed before initialization`

2020-09-10 13:41 UTC, greeflas commented on src/DataFixtures/CategoryFixture.php
> +            $manager->persist($cat);
Нужно задавать уникальное имя, пример:

```php
foreach (self::CATEGORIES as $key => $category) {
  $this->addReference('category_'.$key, $cat);
}
```

2020-09-11 11:40 UTC, Dimaskao commented on src/Repository/CategoryRepository.php
> +    public function getArticleBySlug(string $slug): CategoryPageArticles
БД возвращает массив. Нужно просто сделать сущность которая будет хранить массив из БД?

2020-09-11 12:54 UTC, Dimaskao commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
Добрый день. У меня возникла проблема. БД возвращает пустой массив если в категории нет статей. И если категории не существует - тоже возвращает пустой массив.
Вот запрос
```php
$query = $qb
                ->select('a.id', 'a.title', 'a.image', 'a.publicationDate', 'a.shortDescription')
                ->leftJoin('c.articles', 'a')
                ->where('c.slug = :slug AND a.publicationDate IS NOT NULL')
                ->setParameter('slug', $slug)
                ->getQuery();
```
Как можно понять какой из что именно произошло?

2020-09-11 13:22 UTC, greeflas commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
А дальше как выполняете этот запрос? Каким методом?

2020-09-11 13:23 UTC, Dimaskao commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
$result = $query->getResult();

2020-09-11 13:26 UTC, greeflas commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
```php
$query = $this->createQueryBuilder('c')
  ->leftJoin('c.articles', 'a')
  ->where('c.slug = :slug')
  ->setParameter('slug', $slug)
  ->andWhere('a.publicationDate IS NOT NULL')
  ->getQuery()
;

$category = $query->getOneOrNullResult();
```

2020-09-11 13:51 UTC, Dimaskao commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
А как из этого получить статьи. Я пробую через `$category->getArticles()`, вот что выводит
```
^ Doctrine\ORM\PersistentCollection {#364 ▼
  -snapshot: []
  -owner: App\Entity\Category {#309 ▼
    -id: 101
    -name: "World"
    -articles: Doctrine\ORM\PersistentCollection {#364}
    -slug: "world"
  }
  -association: array:15 [ …15]
  -em: Doctrine\ORM\EntityManager {#169 …11}
  -backRefFieldName: "category"
  -typeClass: Doctrine\ORM\Mapping\ClassMetadata {#320 …}
  -isDirty: false
  #collection: Doctrine\Common\Collections\ArrayCollection {#361 ▼
    -elements: []
  }
  #initialized: false
}
```
Но я не понимаю как из этого получить статьи.

2020-09-11 15:42 UTC, greeflas commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
Все правильно, это коллекция статей.
https://www.doctrine-project.org/projects/doctrine-collections/en/1.6/index.html

2020-09-11 16:10 UTC, Dimaskao commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
Спасибо, но как я понял `$query->getOneOrNullResult()` возвращает только 1 результат, а мне нада все статьи.

2020-09-11 16:33 UTC, Dimaskao commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
Я понял как получить все стати, через `->toArray()`. Но вот почему попадают не опубликованные статьи...

2020-09-12 07:35 UTC, greeflas commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
Попробуйте добавить к запросу `addSelect('a')`. Все правильно, вы получаете одну категорию и уже из нее достаете статьи через `$category->getArticles()`.

2020-09-12 11:02 UTC, Dimaskao commented on src/Controller/CategoryController.php
> +            throw new NotFoundArticlesForCategoryException($slug);
Спасибо, разобрался.

2020-09-17 08:25 UTC, merged